#!/bin/bash
# Copyright (C) 2018 Marco Steiger <marco1steiger@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#------------------------------------------------------------------------

BATTERY="BAT0"

WATTAGE=$(cat /sys/class/power_supply/$BATTERY/power_now)

tr -d '\n' <<< $(bc <<< "scale=1;$WATTAGE / 1000000")
echo W
